import Link from "next/link"; import {Header,Footer,Arrow,ProductImage} from "./components";
import { CustomerTestimonials } from "./home/CustomerTestimonials";
const reasons=[["01","Focused engineering","One core platform allows deeper attention to performance, usability and reliability."],["02","Controlled quality","Product development and production operate within an ISO 13485 quality framework."],["03","Responsive supply","Clear communication and structured planning support distributors and OEM partners."]];
export default function Home(){return <><Header/><main>
  <section className="home-hero hero-light"><div className="hero-background" aria-hidden="true"/><div className="wrap home-hero-grid"><div className="hero-copy"><p className="kicker">GLOBAL MEDICAL DEVICE MANUFACTURER</p><h1>Focused technology.<br/><em>Reliable therapy.</em></h1><p>We develop and manufacture a professional radial shockwave therapy system for distributors, healthcare providers and OEM partners worldwide.</p><div className="hero-actions"><Link className="solid-btn" href="/products">Explore the system <Arrow/></Link><Link className="text-btn" href="/contact">Become a partner <Arrow/></Link></div><div className="hero-meta"><span>Built for</span><b>Medical distributors</b><b>Therapy providers</b><b>OEM partners</b></div></div><span className="hero-model">RADIAL SHOCKWAVE SYSTEM / ST100</span></div></section>
  <section className="trust-strip"><div className="wrap"><span>COMPLIANCE & PARTNERSHIP CAPABILITIES</span><div><b>FDA</b><small>U.S. market pathway</small></div><div><b>FSA / HSA</b><small>Multi-market support</small></div><div><b>OEM / ODM</b><small>Flexible cooperation</small></div></div></section>
  <section className="section wrap"><div className="section-heading"><div><p className="kicker">CORE PRODUCT</p><h2>Engineered around<br/>professional use.</h2></div><div><p>A focused system that combines direct physical control, a clear touchscreen interface and interchangeable applicators.</p><Link className="text-btn" href="/products">View product details <Arrow/></Link></div></div><div className="product-feature"><div className="feature-image"><ProductImage/><span>PRODUCT SYSTEM / 01</span></div><div className="feature-copy"><p className="kicker">SHOCKWAVE THERAPY SYSTEM</p><h3>Clear operation. Consistent output.</h3><p>Designed for professional therapy environments where intuitive operation, repeatable settings and practical maintenance matter.</p><ul><li><span>01</span><div><b>Dual operation modes</b><small>Touchscreen presets and physical adjustment knobs.</small></div></li><li><span>02</span><div><b>Engineered handpiece</b><small>Durable construction for stable everyday use.</small></div></li><li><span>03</span><div><b>Seven applicator heads</b><small>Flexible configuration for different treatment areas.</small></div></li></ul><Link className="solid-btn" href="/contact">Request specifications <Arrow/></Link></div></div></section>
  <section className="blue-section"><div className="wrap"><div className="section-heading inverse"><div><p className="kicker light">WHY AVEN</p><h2>A focused manufacturer.<br/><em>A dependable partner.</em></h2></div><p>Our scale keeps communication direct while our systems keep development and production controlled.</p></div><div className="reason-grid">{reasons.map(r=><article key={r[0]}><span>{r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p></article>)}</div></div></section>
  {false && <>
    <section className="section wrap"><div className="section-heading"><div><p className="kicker">QUALITY & MANUFACTURING</p><h2>From design intent<br/>to released product.</h2></div><div><p>Documented controls connect product requirements, supplier quality, assembly, inspection and final release.</p><Link className="text-btn" href="/quality">Explore quality assurance <Arrow/></Link></div></div><div className="process"><div><span>01</span><b>Design control</b></div><div><span>02</span><b>Supplier quality</b></div><div><span>03</span><b>Controlled assembly</b></div><div><span>04</span><b>Inspection & release</b></div></div></section>
    <section className="partner-cta"><div className="wrap"><div><p className="kicker light">GLOBAL PARTNERSHIP</p><h2>Bring a focused therapy<br/>solution to your market.</h2></div><div><p>We support distributor evaluation, OEM discussions and hospital procurement with clear product, quality and commercial documentation.</p><Link className="solid-btn white" href="/contact">Talk to our team <Arrow/></Link></div></div></section>
  </>}
  <CustomerTestimonials/>
</main><Footer/></>}
